# Generated by Django 5.2.17 on 2026-10-02 02:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cdp_core', '0013_cdp360_identity_unification_enrichment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowMarketplaceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('template_data', models.JSONField()),
                ('source_bioms', models.JSONField(default=list)),
                ('target_bioms', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('icon', models.CharField(default='zap', max_length=50)),
                ('install_count', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('is_official', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-install_count'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('context_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('delegated', 'Delegated'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('approver_role', models.CharField(blank=True, max_length=100)),
                ('approval_level', models.PositiveIntegerField(default=1)),
                ('max_levels', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('escalation_role', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdp_core.company')),
                ('current_approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
                ('delegated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_approvals', to=settings.AUTH_USER_MODEL)),
                ('escalation_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('delegated', 'Delegated'), ('escalated', 'Escalated'), ('commented', 'Commented')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='flow_engine.approvalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='FlowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('cross_biom', 'Cross-BIOM Automation'), ('approval', 'Approval Workflow'), ('onboarding', 'Onboarding'), ('escalation', 'Escalation'), ('notification', 'Notification'), ('ai_triggered', 'AI-Triggered'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('trigger_type', models.CharField(choices=[('event', 'Domain Event'), ('schedule', 'Cron Schedule'), ('manual', 'Manual Trigger'), ('ai', 'AI Agent Trigger'), ('webhook', 'Inbound Webhook')], max_length=50)),
                ('trigger_event', models.CharField(blank=True, max_length=255)),
                ('trigger_schedule', models.CharField(blank=True, max_length=100)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('icon', models.CharField(default='zap', max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_definitions', to='cdp_core.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_approval', 'Waiting for Approval'), ('waiting_input', 'Waiting for Input'), ('waiting_delay', 'Waiting (Delayed)'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('compensating', 'Compensating (Rollback)')], default='pending', max_length=30)),
                ('trigger_payload', models.JSONField(default=dict)),
                ('context', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_node_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdp_core.company')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='flow_engine.flowdefinition')),
                ('trigger_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_executions', to='cdp_core.rawevent')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='flow_engine.flowexecution'),
        ),
        migrations.CreateModel(
            name='FlowSLAPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('flow', 'Entire Flow'), ('node', 'Specific Node')], max_length=10)),
                ('target_node_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('warning_threshold_minutes', models.PositiveIntegerField(default=60)),
                ('breach_threshold_minutes', models.PositiveIntegerField(default=240)),
                ('warning_action', models.JSONField(default=dict)),
                ('breach_action', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_policies', to='flow_engine.flowdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='FlowVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('canvas_data', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='flow_engine.flowdefinition')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('flow', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('trigger', 'Trigger'), ('condition', 'Condition (If/Else)'), ('switch', 'Switch (Multi-Branch)'), ('delay', 'Delay / Timer'), ('parallel_fork', 'Parallel Fork'), ('parallel_join', 'Parallel Join'), ('loop', 'Loop / Iterator'), ('end', 'End'), ('action', 'BIOM Action'), ('ai_action', 'AI Action'), ('http_request', 'HTTP Request'), ('transform', 'Data Transform'), ('notification', 'Send Notification'), ('approval', 'Approval Gate'), ('manual_task', 'Manual Task'), ('form_input', 'Form Input'), ('integration', 'Integration Action'), ('webhook_out', 'Outbound Webhook')], max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('config', models.JSONField(default=dict)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('retry_delay_seconds', models.PositiveIntegerField(default=60)),
                ('compensation_config', models.JSONField(blank=True, default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='flow_engine.flowversion')),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
                'unique_together': {('version', 'node_id')},
            },
        ),
        migrations.AddField(
            model_name='flowexecution',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='flow_engine.flowversion'),
        ),
        migrations.CreateModel(
            name='FlowEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('edge_id', models.CharField(max_length=100)),
                ('source_node', models.CharField(max_length=100)),
                ('target_node', models.CharField(max_length=100)),
                ('source_handle', models.CharField(blank=True, max_length=50)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='flow_engine.flowversion')),
            ],
        ),
        migrations.CreateModel(
            name='StepExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canvas_node_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('waiting', 'Waiting'), ('compensated', 'Compensated')], default='pending', max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='flow_engine.flowexecution')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow_engine.flownode')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLATimer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('warning', 'Warning Sent'), ('breached', 'Breached'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('warning_at', models.DateTimeField()),
                ('breach_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_timers', to='flow_engine.flowexecution')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow_engine.flowslapolicy')),
                ('step_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flow_engine.stepexecution')),
            ],
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='step_execution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='flow_engine.stepexecution'),
        ),
        migrations.CreateModel(
            name='FlowAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('actor_type', models.CharField(max_length=20)),
                ('flow_id', models.UUIDField(blank=True, null=True)),
                ('execution_id', models.UUIDField(blank=True, null=True)),
                ('step_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdp_core.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='flow_engine_company_6d0212_idx'), models.Index(fields=['flow_id', '-created_at'], name='flow_engine_flow_id_82da41_idx'), models.Index(fields=['execution_id', '-created_at'], name='flow_engine_executi_922e13_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='flowexecution',
            index=models.Index(fields=['company', 'status'], name='flow_engine_company_7561b2_idx'),
        ),
        migrations.AddIndex(
            model_name='flowexecution',
            index=models.Index(fields=['flow', '-created_at'], name='flow_engine_flow_id_ac6abf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flowedge',
            unique_together={('version', 'edge_id')},
        ),
        migrations.AddIndex(
            model_name='stepexecution',
            index=models.Index(fields=['execution', 'canvas_node_id'], name='flow_engine_executi_aa2855_idx'),
        ),
        migrations.AddIndex(
            model_name='slatimer',
            index=models.Index(fields=['status', 'warning_at'], name='flow_engine_status_650454_idx'),
        ),
        migrations.AddIndex(
            model_name='slatimer',
            index=models.Index(fields=['status', 'breach_at'], name='flow_engine_status_053225_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['current_approver', 'status'], name='flow_engine_current_424bee_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['company', 'status'], name='flow_engine_company_c1049a_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['deadline'], name='flow_engine_deadlin_64393f_idx'),
        ),
    ]
