# Generated by Django 5.2.17 on 2026-10-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stepexecution',
            name='flow_engine_executi_aa2855_idx',
        ),
        migrations.RenameField(
            model_name='flownode',
            old_name='node_id',
            new_name='canvas_node_id',
        ),
        migrations.AlterUniqueTogether(
            name='flownode',
            unique_together={('version', 'canvas_node_id')},
        ),
        migrations.AddIndex(
            model_name='stepexecution',
            index=models.Index(fields=['execution', 'node_id'], name='flow_engine_executi_61356c_idx'),
        ),
    ]
