# Generated by Django 5.2.17 on 2026-09-03 20:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0012_alter_auditlog_action_segment'),
        ('service', '0002_serviceticket_first_responded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback_rating', models.PositiveSmallIntegerField(blank=True, help_text='1 to 5 stars', null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('guarantee_period', models.CharField(help_text="e.g. '12 Months', '2 Years'", max_length=100)),
                ('is_guarantee_active', models.BooleanField(default=True)),
                ('return_issued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_entitlements', to='cdp_core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_entitlements', to='cdp_core.customer')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
    ]
