# Generated by Django 5.2.17 on 2026-09-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_serviceentitlement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceentitlement',
            name='is_guarantee_active',
        ),
        migrations.AddField(
            model_name='serviceentitlement',
            name='guarantee_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
