# Generated by Django 5.2.17 on 2026-09-03 20:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0012_alter_auditlog_action_segment'),
        ('marketing', '0002_lead_company_name_lead_lead_score_lead_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('spend', 'Campaign Spend (Expense)'), ('roi', 'Attributed Revenue (ROI)')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketing.campaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_transactions', to='cdp_core.company')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
