# Generated by Django 5.2.17 on 2026-10-01 04:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0013_cdp360_identity_unification_enrichment'),
        ('marketing', '0003_campaigntransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ai_audience_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ai_copy_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ai_send_time_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='attribution_window_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Frozen audience metadata at send time'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='avg_propensity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bandit_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bandit_exploration_rate',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bandit_metric',
            field=models.CharField(blank=True, choices=[('open_rate', 'Open Rate'), ('click_rate', 'Click Rate'), ('conversion_rate', 'Conversion Rate')], default='click_rate', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bandit_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('one_time', 'One-Time Blast'), ('automated', 'Automated Journey'), ('triggered', 'Event-Triggered')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('digital_ads', 'Digital Ads'), ('web_engagement', 'Web Engagement')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='churn_risk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='estimated_audience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal_event',
            field=models.CharField(blank=True, help_text='Conversion event name e.g. deal.won', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_bounced',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_clicked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_converted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_delivered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_opened',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_unsubscribed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='AttributionTouchpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touchpoint_type', models.CharField(choices=[('impression', 'Ad Impression'), ('email_open', 'Email Open'), ('email_click', 'Email Click'), ('sms_reply', 'SMS Reply'), ('web_visit', 'Web Visit'), ('form_submit', 'Form Submit'), ('conversion', 'Conversion')], max_length=20)),
                ('channel', models.CharField(max_length=20)),
                ('first_touch_weight', models.FloatField(default=0.0)),
                ('last_touch_weight', models.FloatField(default=0.0)),
                ('linear_weight', models.FloatField(default=0.0)),
                ('time_decay_weight', models.FloatField(default=0.0)),
                ('position_based_weight', models.FloatField(default=0.0)),
                ('attributed_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touchpoints', to='marketing.campaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribution_touchpoints', to='cdp_core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribution_touchpoints', to='cdp_core.customer')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(default='A', max_length=50)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('preview_text', models.CharField(blank=True, max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('body_plain', models.TextField(blank=True)),
                ('message_text', models.TextField(blank=True)),
                ('cta_url', models.URLField(blank=True)),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('bandit_alpha', models.FloatField(default=1.0, help_text='Successes + prior')),
                ('bandit_beta', models.FloatField(default=1.0, help_text='Failures + prior')),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('successes', models.PositiveIntegerField(default=0)),
                ('traffic_percentage', models.PositiveIntegerField(default=100)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_generation_prompt', models.TextField(blank=True)),
                ('ai_source_references', models.JSONField(blank=True, default=list)),
                ('is_template', models.BooleanField(default=False)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='marketing.campaign')),
            ],
            options={
                'ordering': ['variant_name'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='bandit_winner_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_campaigns', to='marketing.campaigncontent'),
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_address', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('optimized', 'Send-Time Optimized'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('converted', 'Converted'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('optimal_send_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('propensity_score', models.FloatField(default=0.0)),
                ('churn_risk', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='marketing.campaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to='cdp_core.company')),
                ('content_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='marketing.campaigncontent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to='cdp_core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('converted', 'Converted'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed'), ('complained', 'Complained')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marketing.campaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_events', to='cdp_core.company')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marketing.campaignrecipient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_exclusion', models.BooleanField(default=False, help_text="If True, exclude this segment's audience")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_segments', to='marketing.campaign')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_segments', to='cdp_core.segment')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='campaigns', through='marketing.CampaignSegment', to='cdp_core.segment'),
        ),
        migrations.CreateModel(
            name='CampaignPropensityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_probability', models.FloatField(default=0.0)),
                ('churn_probability', models.FloatField(default=0.0)),
                ('optimal_send_hour', models.PositiveIntegerField(blank=True, null=True)),
                ('optimal_send_day', models.PositiveIntegerField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1', max_length=50)),
                ('features_snapshot', models.JSONField(blank=True, default=dict)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propensity_scores', to='marketing.campaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_propensity_scores', to='cdp_core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propensity_scores', to='cdp_core.customer')),
            ],
            options={
                'unique_together': {('campaign', 'customer')},
            },
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='marketing_c_campaig_5ad1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['customer', 'campaign'], name='marketing_c_custome_c8442d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['optimal_send_at'], name='marketing_c_optimal_d3acdc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'customer')},
        ),
        migrations.AddIndex(
            model_name='campaignevent',
            index=models.Index(fields=['campaign', 'event_type'], name='marketing_c_campaig_2d4375_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignsegment',
            unique_together={('campaign', 'segment')},
        ),
    ]
