# Generated by Django 5.2.16 on 2026-07-18 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0004_company_customer_company_eventschema_company_and_more'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdp_core.company'),
        ),
        migrations.AddField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cdp_core.company'),
        ),
    ]
