# Generated by Django 5.2.17 on 2026-08-29 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0007_alter_customer_primary_email_and_more'),
        ('crm', '0002_contact_company_deal_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='cdp_core.customer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.contact'),
        ),
    ]
