# Generated by Django 5.2.17 on 2026-08-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_deal_customer_alter_deal_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='title',
            field=models.CharField(default='New Deal', max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('lead', 'Lead'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='lead', max_length=20),
        ),
    ]
