# Generated by Django 5.2.17 on 2026-08-31 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0011_company_config_company_plan_company_updated_at_and_more'),
        ('crm', '0004_deal_expected_close_date_deal_title_alter_deal_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='cdp_core.account'),
        ),
        migrations.AddField(
            model_name='deal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='cdp_core.account'),
        ),
    ]
