# Generated by Django 5.2.17 on 2026-10-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_deal_forecast_category_deal_health_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('lead', 'Lead'), ('opportunity', 'Opportunity'), ('proposal', 'Proposal'), ('won', 'Won'), ('lost', 'Lost')], default='lead', max_length=20),
        ),
    ]
