# Generated by Django 5.2.16 on 2026-07-18 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Enforces domain.action naming convention (e.g., user.logged_in)', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Event name must contain at least one dot, use lowercase letters, and have no spaces.', regex='^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$')])),
                ('json_schema', models.JSONField(help_text='JSON schema validating raw payload for this event type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('raw_payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
