# Generated by Django 5.2.16 on 2026-07-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0002_customer_rawevent_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='consent',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
