# Generated by Django 5.2.16 on 2026-07-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0004_company_customer_company_eventschema_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to revoke API access.'),
        ),
    ]
