# Generated by Django 5.2.16 on 2026-07-25 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0005_company_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschema',
            name='event_name',
            field=models.CharField(help_text='Enforces domain.action naming convention (e.g., user.logged_in)', max_length=255, validators=[django.core.validators.RegexValidator(message='Event name must contain at least one dot, use lowercase letters, and have no spaces.', regex='^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventschema',
            unique_together={('company', 'event_name')},
        ),
    ]
