# Generated by Django 5.2.17 on 2026-08-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0006_alter_eventschema_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('company', 'primary_email'), name='unique_company_email'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('company', 'primary_phone'), name='unique_company_phone'),
        ),
    ]
