# Generated by Django 5.2.17 on 2026-08-29 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0007_alter_customer_primary_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trigger_event', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('condition_field', models.CharField(blank=True, max_length=255)),
                ('condition_operator', models.CharField(blank=True, max_length=50)),
                ('condition_value', models.CharField(blank=True, max_length=255)),
                ('action_type', models.CharField(max_length=255)),
                ('action_event_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='cdp_core.company')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_executions', to='cdp_core.rawevent')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='cdp_core.workflow')),
            ],
            options={
                'unique_together': {('workflow', 'raw_event')},
            },
        ),
    ]
