# Generated by Django 5.2.17 on 2026-08-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0008_workflow_workflowexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='destination_biom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workflow',
            name='source_biom',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
