# Generated by Django 5.2.17 on 2026-08-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0009_workflow_destination_biom_workflow_source_biom'),
    ]

    operations = [
    ]
