# Generated by Django 5.2.17 on 2026-08-31 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0011_company_config_company_plan_company_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('merge', 'Merge'), ('export', 'Export'), ('access', 'Access'), ('anonymize', 'Anonymize')], max_length=20),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rules', models.JSONField(blank=True, default=list, help_text="List of rules e.g. [{'field': 'attributes.tier', 'operator': '==', 'value': 'enterprise'}]")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='cdp_core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
