# Generated by Django 5.2.17 on 2026-09-04 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdp_core', '0012_alter_auditlog_action_segment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CDPPipelineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_events_ingested', models.IntegerField(default=0)),
                ('events_today', models.IntegerField(default=0)),
                ('events_pending', models.IntegerField(default=0)),
                ('events_errors', models.IntegerField(default=0)),
                ('ingestion_active', models.BooleanField(default=True)),
                ('deterministic_matches', models.IntegerField(default=0)),
                ('ml_batch_queue_size', models.IntegerField(default=0)),
                ('auto_merged_count', models.IntegerField(default=0)),
                ('suggested_merges_pending', models.IntegerField(default=0)),
                ('last_batch_run', models.DateTimeField(blank=True, null=True)),
                ('identity_active', models.BooleanField(default=True)),
                ('unified_profiles_count', models.IntegerField(default=0)),
                ('unification_active', models.BooleanField(default=True)),
                ('enriched_profiles_count', models.IntegerField(default=0)),
                ('enrichment_active', models.BooleanField(default=True)),
                ('active_segments_count', models.IntegerField(default=0)),
                ('total_segment_audience', models.IntegerField(default=0)),
                ('intelligence_active', models.BooleanField(default=True)),
                ('consent_opt_in', models.IntegerField(default=0)),
                ('consent_opt_out', models.IntegerField(default=0)),
                ('consent_pending', models.IntegerField(default=0)),
                ('dsar_requests', models.IntegerField(default=0)),
                ('rtbf_erasures', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cdp_pipeline_status', to='cdp_core.company')),
            ],
        ),
        migrations.CreateModel(
            name='MergeSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_score', models.FloatField(help_text='0.0-1.0 confidence that these are the same person')),
                ('match_reasons', models.JSONField(blank=True, default=list, help_text='e.g. [{"field": "email_domain", "score": 0.9}]')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_merged', 'Auto-Merged')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_suggestions', to='cdp_core.company')),
                ('primary_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_suggestions_primary', to='cdp_core.customer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('secondary_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_suggestions_secondary', to='cdp_core.customer')),
            ],
            options={
                'ordering': ['-confidence_score'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_page_views', models.IntegerField(default=0)),
                ('total_events', models.IntegerField(default=0)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('primary_interest_category', models.CharField(blank=True, max_length=255)),
                ('engagement_score', models.FloatField(default=0.0, help_text='0-100 engagement score')),
                ('lifecycle_stage', models.CharField(choices=[('anonymous', 'Anonymous'), ('known', 'Known'), ('engaged', 'Engaged'), ('qualified', 'Marketing Qualified'), ('opportunity', 'Sales Opportunity'), ('customer', 'Customer'), ('advocate', 'Advocate'), ('churned', 'Churned')], default='anonymous', max_length=30)),
                ('engagement_tier', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot'), ('on_fire', 'On Fire')], default='cold', max_length=20)),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_country', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('enrichment_source', models.CharField(blank=True, max_length=100)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('channels_active', models.JSONField(blank=True, default=list)),
                ('device_fingerprints', models.JSONField(blank=True, default=list)),
                ('consent_status', models.CharField(default='unknown', max_length=30)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('analytics_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_profiles', to='cdp_core.company')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unified_profile', to='cdp_core.customer')),
            ],
            options={
                'ordering': ['-engagement_score'],
            },
        ),
        migrations.CreateModel(
            name='IdentityEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('device_id', 'Device ID'), ('cookie_id', 'Cookie ID'), ('external_id', 'External ID'), ('ip_address', 'IP Address')], max_length=50)),
                ('identity_value', models.CharField(db_index=True, max_length=512)),
                ('confidence', models.FloatField(default=1.0, help_text='1.0 = deterministic match')),
                ('source', models.CharField(default='ingestion', help_text='ingestion, ml_batch, manual', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_edges', to='cdp_core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_edges', to='cdp_core.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'identity_type', 'identity_value'], name='cdp_core_id_company_704bda_idx')],
                'unique_together': {('company', 'identity_type', 'identity_value')},
            },
        ),
    ]
